name: Mezcla HUXXX -> develop -> release -> master
on:
    push:
        branches:
            - 'develop'
jobs:
    job1:
        name: Pruebas
        if: ${{ contains(github.event.head_commit.message, 'RELEASE') }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout de repositorio
          uses: actions/checkout@v2
        - name: Configuración de entorno de python
          uses: actions/setup-python@v2
          with:
              python-version: '3.7'
        - name: Instalación de librerías y dependencias
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Correr pruebas
          id: correr-pruebas
          run: python -m unittest -v tests/test_persona.py
        - name: Cálculo de cubrimiento
          id: cubrimiento
          run: |
              coverage run -m unittest tests/test_persona.py
              coverage report -m
    automerge:
        name: Automerge Develop
        needs: job1
        runs-on: ubuntu-latest
        steps:
        - name: Mezcla rama Historias -> rama Develop
          uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            source-branch: ${{ github.ref_name }}
            target-branch: develop
    job2:
      name: Crear rama release
      needs: [job1, automerge]
      runs-on: ubuntu-latest
      steps:
      - name: Crear rama
        run: |
          git checkout -b release
          git push -f -u origin release
    automerge2:
      name: Automerge Master
      needs: job2
      runs-on: ubuntu-latest
      steps:
      - name: Mezcla rama release -> rama master
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          source-branch: release
          target-branch: master