name: Mezcla historia a rama develop
on:
    push:
        branches:
            - 'HU**'
jobs:
    job1:
        name: Pruebas MERGE
        if: ${{ contains(github.event.head_commit.message, 'MERGE') }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout de repositorio
          uses: actions/checkout@v2
        - name: Configuración de entorno de python
          uses: actions/setup-python@v2
          with:
              python-version: '3.7'
        - name: Instalación de librerías y dependencias
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Correr pruebas
          id: correr-pruebas
          run: python -m unittest -v tests/test_persona.py
        - name: Cálculo de cubrimiento
          id: cubrimiento
          run: |
              coverage run -m unittest tests/test_persona.py
              coverage report -m
    automerge:
        name: Automerge MERGE
        needs: job1
        runs-on: ubuntu-latest
        steps:
        - name: Mezcla rama Historias -> rama Develop
          uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            source-branch: ${{ github.ref_name }}
            target-branch: develop
    job2:
        name: Pruebas RELEASE
        if: ${{ contains(github.event.head_commit.message, 'RELEASE') }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout de repositorio
          uses: actions/checkout@v2
        - name: Configuración de entorno de python
          uses: actions/setup-python@v2
          with:
               python-version: '3.7'
        - name: Instalación de librerías y dependencias
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Correr pruebas
          id: correr-pruebas
          run: python -m unittest -v tests/test_persona.py
        - name: Cálculo de cubrimiento
          id: cubrimiento
          run: |
            coverage run -m unittest tests/test_persona.py
            coverage report -m
    automerge2:
        name: Automerge HUXXX -> DEVELOP -> RELEASE -> MASTER
        needs: job2
        runs-on: ubuntu-latest
        steps:
        - name: Mezcla rama Historias -> rama Develop
          uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            source-branch: ${{ github.ref_name }}
            target-branch: develop
        - name: Checkout de repositorio
          uses: actions/checkout@v2
        - name: Crear rama RELEASE
          run: |
            git checkout -b release
            git push -f -u origin release
        - name: Mezcla rama release -> rama master
          uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            source-branch: release
            target-branch: master    